name = "analysis-tools"
type = "webpack"
account_id = "1c71f27d6fa097a1576b4ffab9186fa8"
workers_dev = false
route = "*analysis-tools.dev/*"
kv_namespaces = [ 
         { binding = "votes", id = "6f4092d5a6524b8c90abbe3d18eb1a07" } 
]
compatibility_date = "2022-04-05"
main = "workers-site/index.js"

[site]
bucket = "./public"
