---
# yamllint disable rule:line-length
name: Backup

on:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "298.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Backup db
        run: |
          make -C backend backup
